spring.application.name=frisoft

# Credenciales de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/frisoft
spring.datasource.username=postgres
spring.datasource.password=postgres

# Le dice a Spring que cree/actualice las tablas de usuarios automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect