spring.application.name=frisoft

# Credenciales de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/frisoft
spring.datasource.username=postgres
spring.datasource.password=leoncio123

# Le dice a Spring que cree/actualice las tablas de usuarios automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración JWT
app.jwt.secret=SVixaCNlpWmzFlTArToHH7V0zgb3LiKVaA0BvtNb9a3l+9bE17eKx4oyDBNAbygR
app.jwt.expiration=86400000